name: Deploy to Production

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Add server to known hosts
      run: |
        ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

    - name: Deploy to server
      run: |
        ssh ${{ secrets.USER }}@${{ secrets.HOST }} << 'EOF'
            cd /home/ubuntu/bagamba-bot
            git pull
            pwd        
        # Create .env file from GitHub secrets and variables
            echo "${{ secrets.ENVS_B64 }}" | base64 -d > bagamba/.env
            echo "${{ secrets.GOOGLE_TOKEN_B64 }}" | base64 -d > bagamba/credentials.json
          # Deploy with Docker Compose
            pwd
            docker-compose -f docker-compose.yml down
            docker-compose --env-file bagamba/.env -f docker-compose.yml build --no-cache
            docker-compose --env-file bagamba/.env -f docker-compose.yml up -d
          
          
            docker system prune -af
        EOF

    - name: Health check
      run: |
        sleep 20
        curl -f https://bagamba.assistant.instories.com/health/ || exit 1